describe('Galvanize Dinos Local Host Test', () => {
  it('Does The Things', () => {
    cy.visit('/')
    cy.get('#job-listings').find('li').should('have.length.above', '3')
    cy.get('form > input').should('have.value', '')
    cy.get('form > textarea').should('have.value', '')
    cy.get('input[name=title]').type('Job Title')
    cy.get('input[name=pay]').type('Pay')
    cy.get('textarea[name=description]').type('Description')
    cy.get('form > input').should('have.attr', 'name', 'title')
    cy.get('input[type=submit]').click()
    cy.get('form > input').should('have.value', '')
    cy.get('form > textarea').should('have.value', '')
    cy.get('#job-listings li').eq(0).as('topListing')
    cy.get('@topListing').find('h4').contains('Job Title').should('exist')
    cy.get('@topListing').find('small').contains('Pay').should('exist')
    cy.get('@topListing').find('p').contains('Description').should('exist')
    cy.get('@topListing').find('small').contains('0 dinos are interested in this job').should('exist')
  })
})
