describe('Hackernews Website', () => {
  it('Meets E2E Requirements for Deployed Site', () => {
    cy.visit('/')
    cy.get('title').should('contain', 'Vue HN 2.0')
    cy.get('.news-item').should('have.length.above', 1)
    cy.get('.inner a').contains('New').click()
    cy.url().should('contain', 'https://e2e-hackernews.herokuapp.com/new')
    cy.get('.news-item').should('have.length.above', 1)
    cy.get('.news-list').find('.news-item').should('not.exist')
    cy.get('.news-list-nav a').contains('more >').click()
    cy.url().should('contain', 'https://e2e-hackernews.herokuapp.com/new/2')
    cy.get('.news-item').should('have.length.above', 1)
    cy.get('.inner a').contains('Jobs').click()
    cy.url().should('contain', 'https://e2e-hackernews.herokuapp.com/job')
    cy.get('.news-item').should('have.length.above', 1)
  })
})
